# Generated by Django 2.1.8 on 2022-04-23 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naira', models.IntegerField()),
                ('Cedes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('Recipient', models.CharField(max_length=20)),
                ('amount', models.CharField(max_length=20)),
                ('Currency', models.CharField(choices=[('NG', 'NG'), ('GH', 'GH'), ('UK', 'UK')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('successful', 'successful'), ('declined', 'declined')], max_length=12)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='users_wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('credict_ballance', models.CharField(max_length=20)),
                ('Currency', models.CharField(choices=[('NG', 'NG'), ('GH', 'GH'), ('UK', 'UK')], max_length=20)),
                ('Billing_Address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
