# Generated by Django 2.1.8 on 2022-04-23 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi_hiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='Sender',
        ),
    ]
