# Generated by Django 2.1.8 on 2022-04-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hi_hiApp', '0002_auto_20220422_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Recipient',
            new_name='user',
        ),
    ]
