# Generated by Django 2.1.8 on 2022-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hi_hiApp', '0003_auto_20220422_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_wallet',
            name='Currency',
            field=models.CharField(choices=[('NG', 'NG'), ('GH', 'GH'), ('UK', 'UK')], max_length=20, null=True),
        ),
    ]
